### ISSUE TITLE
How to configure the App. 

### ISSUE THREAD

**Issue by isc-gsaito** [danoleg/ai-text-detection#1]
Accessing the https://127.0.0.1:801/config right after docker-compose up finishes to build the app, leads to a page where I have to fill the hostname and password. 

I entered localhost as my hostname and created a password for the username USER. I kept the other parameters on their default values. 

When I press the "Save and Init" button, I get an error "[Errno 111] Connection refused"

Looking at my docker-desktop UI I noticed that the only port exposed by the container is 8010.  So I tried to change the port number from the default value of 1972 to 8010. 

But with this setting, if I press the "Save and Init"  button nothing happens. The page does not refresh. 

Can you please clarify?

**Comment by danoleg** [comment]
This application is designed to work with the Сloud SQL, so there is no docker container with IRIS. I think it will also work with your local IRIS instance, but I haven't tested it. Read more in the README.

**Comment by isc-gsaito** [comment]
I have created a Cloud SQL deployment and then I was able to finish the config and the other steps.
